services:
  - type: web
    name: myquiz-app
    env: node
    #buildCommand: npm run build
    buildCommand: npm install --include=dev && tsc -p tsconfig.server.json && cd client && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      # Ensure devDependencies (e.g., TypeScript types) are installed during build
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: PORT
        value: 10000
    healthCheckPath: /api/vocabulary
    autoDeploy: true
    plan: free
